### ISSUE TITLE
[Notebook Missing] Ask for Upload 

### ISSUE THREAD

**Issue by imbibekk** [Chubasik/yacup_recsys_2022#1]
Thank you the code. 
I'm trying to replicate your solution but looks like `1b5k2eii` notebook is missing. The notebook `ne1l6afj` uses the checkpoint from `1b5k2eii`. So could you please upload the `1b5k2eii` notebook? Thank you

**Comment by Chubasik** [comment]
Thanks for opening this issue! I have added the missing notebook
